language: node_js
matrix:
  include:
    - node_js: "lts/*"
    - node_js: 11
  allow_failures:
    - node_js: 11
install:
  - npm install
  - npm install --only=dev
script:
  - npm run coverage:ci
  - npm run coverage:upload
cache:
  directories:
    - "node_modules"
    - "pki"
    - "certificates"
branches:
  only:
  - master
  - next
  - LTS
